-- Generated by scripts/build_db_rpc.py; fixed SQL only.
BEGIN;
ALTER TABLE public.runs ADD COLUMN IF NOT EXISTS title_locked boolean NOT NULL DEFAULT false;
CREATE SCHEMA IF NOT EXISTS carousel_internal;
REVOKE ALL ON SCHEMA carousel_internal FROM PUBLIC, anon, authenticated;
-- app.services.db:1460
CREATE OR REPLACE FUNCTION carousel_internal.q_66d6ec24b25d3ac190dc(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>1 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; DELETE FROM instagram_accounts WHERE id = (params->>0)::text; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_66d6ec24b25d3ac190dc(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:576
CREATE OR REPLACE FUNCTION carousel_internal.q_db06a33199c9486804a6(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>1 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; DELETE FROM pending_reviews WHERE run_id = (params->>0)::text; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_db06a33199c9486804a6(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:551
CREATE OR REPLACE FUNCTION carousel_internal.q_b9f11b639815277496d7(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>1 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (DELETE FROM pending_reviews WHERE run_id = (params->>0)::text RETURNING run_id, session_id, function_call_id) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_b9f11b639815277496d7(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1135
CREATE OR REPLACE FUNCTION carousel_internal.q_c7ccaf1d349ca9c0b1a8(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>2 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; INSERT INTO app_config (key, value) VALUES ((params->>0)::text, (params->1)::jsonb) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now(); GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_c7ccaf1d349ca9c0b1a8(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1198
CREATE OR REPLACE FUNCTION carousel_internal.q_b9eb5873954e0c5ddb20(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>2 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; INSERT INTO app_users (email, role) VALUES (lower((params->>0)::text), (params->>1)::text) ON CONFLICT (email) DO NOTHING; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_b9eb5873954e0c5ddb20(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1535
CREATE OR REPLACE FUNCTION carousel_internal.q_31b15702d6e871ae9ea7(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>5 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; INSERT INTO carousel_designs ( owner_email, design_id, name, payload, sort_order ) VALUES ((params->>0)::text, (params->>1)::text, (params->>2)::text, (params->3)::jsonb, COALESCE((params->>4)::int4::integer, 0)) ON CONFLICT (owner_email, design_id) DO UPDATE SET name = EXCLUDED.name, payload = EXCLUDED.payload, sort_order = COALESCE((params->>4)::int4::integer, carousel_designs.sort_order), updated_at = now(); GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_31b15702d6e871ae9ea7(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.memory_service:346
CREATE OR REPLACE FUNCTION carousel_internal.q_8dd89723936f1007a918(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>6 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; INSERT INTO feedback (run_id, verdict, feedback, targets, news_title, created_at) VALUES ((params->>0)::text, (params->>1)::text, (params->>2)::text, (params->3)::jsonb, (params->>4)::text, (params->>5)::timestamptz); GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_8dd89723936f1007a918(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:613
CREATE OR REPLACE FUNCTION carousel_internal.q_8221394f0d0a06bc0067(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>7 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (INSERT INTO feedback (run_id, verdict, feedback, targets, news_title, decided_by, source) VALUES ((params->>0)::text, (params->>1)::text, (params->>2)::text, (params->3)::jsonb, (params->>4)::text, (params->>5)::text, (params->>6)::text) RETURNING id) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_8221394f0d0a06bc0067(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1395
CREATE OR REPLACE FUNCTION carousel_internal.q_257f54c3425331ee9258(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>10 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; INSERT INTO instagram_accounts ( id, ig_user_id, username, name, avatar_key, auth_kind, token_enc, token_expires_at, is_default, connected_by ) VALUES ((params->>0)::text, (params->>1)::text, (params->>2)::text, (params->>3)::text, (params->>4)::text, (params->>5)::text, (params->>6)::text, (params->>7)::timestamptz, (params->>8)::bool, (params->>9)::text) ON CONFLICT (ig_user_id) DO UPDATE SET username = EXCLUDED.username, name = EXCLUDED.name, avatar_key = COALESCE(NULLIF(EXCLUDED.avatar_key, ''), instagram_accounts.avatar_key), auth_kind = EXCLUDED.auth_kind, token_enc = EXCLUDED.token_enc, token_expires_at = EXCLUDED.token_expires_at, disabled = false, connected_by = EXCLUDED.connected_by, last_refreshed_at = now(); GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_257f54c3425331ee9258(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.memory_service:247
CREATE OR REPLACE FUNCTION carousel_internal.q_5f15232ef02472dda91c(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>8 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; INSERT INTO memory_entries (app_name, user_id, session_id, event_id, author, role, text_content, event_ts) VALUES ((params->>0)::text, (params->>1)::text, (params->>2)::text, (params->>3)::text, (params->>4)::text, (params->>5)::text, (params->>6)::text, (params->>7)::text) ON CONFLICT (app_name, user_id, session_id, event_id) DO NOTHING; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_5f15232ef02472dda91c(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:119
CREATE OR REPLACE FUNCTION carousel_internal.q_5703021faed72a1fc5ea(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>4 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (INSERT INTO news_queue (id, url_hash, payload, status) VALUES ((params->>0)::text, (params->>1)::text, (params->2)::jsonb, (params->>3)::text) ON CONFLICT (url_hash) DO NOTHING RETURNING id) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_5703021faed72a1fc5ea(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:469
CREATE OR REPLACE FUNCTION carousel_internal.q_39816ede3cb98f6fa805(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>3 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; INSERT INTO pending_reviews (run_id, session_id, function_call_id) VALUES ((params->>0)::text, (params->>1)::text, (params->>2)::text) ON CONFLICT (run_id) DO UPDATE SET session_id = EXCLUDED.session_id, function_call_id = EXCLUDED.function_call_id, created_at = now(); GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_39816ede3cb98f6fa805(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1044
CREATE OR REPLACE FUNCTION carousel_internal.q_142f5eb3b635be7999e6(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>6 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; INSERT INTO run_events (run_id, seq, kind, author, text, data) VALUES ((params->>0)::text, (params->>1)::int4, (params->>2)::text, (params->>3)::text, (params->>4)::text, (params->5)::jsonb) ON CONFLICT (run_id, seq) DO NOTHING; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_142f5eb3b635be7999e6(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:372
CREATE OR REPLACE FUNCTION carousel_internal.q_81d29b5a1246b41abffa(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>2 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; INSERT INTO runs (run_id, news_id, phase, review_round) VALUES ((params->>0)::text, (params->>1)::text, 'generate', 0) ON CONFLICT (run_id) DO UPDATE SET news_id = EXCLUDED.news_id, updated_at = now(); GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_81d29b5a1246b41abffa(jsonb) FROM PUBLIC,anon,authenticated;

-- web_api.routes_runs:194
CREATE OR REPLACE FUNCTION carousel_internal.q_d01506a7a95cb13ae4a6(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>4 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT (SELECT jsonb_object_agg(key, value) FROM jsonb_each(CASE WHEN jsonb_typeof(state) = 'string' THEN (state #>> '{}')::jsonb ELSE COALESCE(state, '{}'::jsonb) END) WHERE key = ANY((CASE WHEN params->3='null'::jsonb THEN NULL ELSE ARRAY(SELECT jsonb_array_elements_text(params->3))::text[] END)::text[])) AS state FROM public.sessions WHERE app_name = (params->>0)::text AND user_id = (params->>1)::text AND id = (params->>2)::text) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_d01506a7a95cb13ae4a6(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:813
CREATE OR REPLACE FUNCTION carousel_internal.q_494f276d0c2e73072b8e(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>4 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT * FROM runs WHERE ((params->>0)::timestamptz::timestamptz IS NULL OR created_at < (params->>0)::timestamptz) AND ((params->>1)::text::text IS NULL OR phase = (params->>1)::text) AND ((params->>2)::text::text IS NULL OR status = (params->>2)::text) ORDER BY created_at DESC LIMIT (params->>3)::int8) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_494f276d0c2e73072b8e(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:909
CREATE OR REPLACE FUNCTION carousel_internal.q_01773445dea14a19d433(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>3 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT * FROM runs WHERE phase = ANY((CASE WHEN params->0='null'::jsonb THEN NULL ELSE ARRAY(SELECT jsonb_array_elements_text(params->0))::text[] END)::text[]) AND status <> ALL((CASE WHEN params->1='null'::jsonb THEN NULL ELSE ARRAY(SELECT jsonb_array_elements_text(params->1))::text[] END)::text[]) AND updated_at < now() - make_interval(secs => (params->>2)::float8) ORDER BY created_at DESC) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_01773445dea14a19d433(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:794
CREATE OR REPLACE FUNCTION carousel_internal.q_b15c77692c7f308c6c33(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>1 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT * FROM runs WHERE run_id = (params->>0)::text) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_b15c77692c7f308c6c33(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1481
CREATE OR REPLACE FUNCTION carousel_internal.q_edc732ff5423b6c65644(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>1 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT account_id FROM runs WHERE run_id = (params->>0)::text) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_edc732ff5423b6c65644(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1195
CREATE OR REPLACE FUNCTION carousel_internal.q_d5878fa1b98bfc26a50b(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>0 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT count(*) FROM app_users) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_d5878fa1b98bfc26a50b(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1215
CREATE OR REPLACE FUNCTION carousel_internal.q_f2fa2c19619b8853c24c(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>3 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT count(*) FROM public.events WHERE app_name = (params->>0)::text AND user_id = (params->>1)::text AND session_id = (params->>2)::text) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_f2fa2c19619b8853c24c(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:877
CREATE OR REPLACE FUNCTION carousel_internal.q_e263c30765e201849caa(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>1 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT count(*) FROM runs WHERE created_at >= (params->>0)::timestamptz) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_e263c30765e201849caa(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1157
CREATE OR REPLACE FUNCTION carousel_internal.q_b337d4a5a13f14e7f3c1(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>1 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT email, role, disabled FROM app_users WHERE lower(email) = lower((params->>0)::text)) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_b337d4a5a13f14e7f3c1(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1167
CREATE OR REPLACE FUNCTION carousel_internal.q_c0445461a72264308f2b(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>0 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT email, role, disabled, created_at FROM app_users ORDER BY email) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_c0445461a72264308f2b(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:133
CREATE OR REPLACE FUNCTION carousel_internal.q_538c2d6dde84e4ab4e0f(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>1 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT id FROM news_queue WHERE url_hash = (params->>0)::text) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_538c2d6dde84e4ab4e0f(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.memory_service:286
CREATE OR REPLACE FUNCTION carousel_internal.q_b6f610789162c99e43ef(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>4 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT id, author, role, text_content, event_ts, created_at FROM memory_entries WHERE app_name=(params->>0)::text AND user_id=(params->>1)::text AND text_content ILIKE ANY((CASE WHEN params->2='null'::jsonb THEN NULL ELSE ARRAY(SELECT jsonb_array_elements_text(params->2))::text[] END)::text[]) ORDER BY created_at DESC LIMIT (params->>3)::int8) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_b6f610789162c99e43ef(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1367
CREATE OR REPLACE FUNCTION carousel_internal.q_793e6c2b2cae23805dbb(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>0 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT id, ig_user_id, username, name, avatar_key, auth_kind, token_enc, token_expires_at, is_default, disabled, connected_by, connected_at, last_refreshed_at FROM instagram_accounts ORDER BY username) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_793e6c2b2cae23805dbb(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1339
CREATE OR REPLACE FUNCTION carousel_internal.q_dcf939d0ed39e5939414(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>2 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT id, payload FROM news_queue WHERE id = (params->>0)::text AND status <> (params->>1)::text) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_dcf939d0ed39e5939414(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:198
CREATE OR REPLACE FUNCTION carousel_internal.q_1278e6f6628786a1cee6(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>2 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT id, payload, created_at FROM news_queue WHERE status = (params->>0)::text ORDER BY created_at ASC LIMIT (params->>1)::int8) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_1278e6f6628786a1cee6(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.memory_service:290
CREATE OR REPLACE FUNCTION carousel_internal.q_8d6a6ed71afeda6dd765(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>2 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT id, run_id, verdict, feedback, targets, news_title, created_at FROM feedback WHERE feedback ILIKE ANY((CASE WHEN params->0='null'::jsonb THEN NULL ELSE ARRAY(SELECT jsonb_array_elements_text(params->0))::text[] END)::text[]) OR news_title ILIKE ANY((CASE WHEN params->0='null'::jsonb THEN NULL ELSE ARRAY(SELECT jsonb_array_elements_text(params->0))::text[] END)::text[]) ORDER BY created_at DESC LIMIT (params->>1)::int8) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_8d6a6ed71afeda6dd765(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1277
CREATE OR REPLACE FUNCTION carousel_internal.q_6a10b8fa3f5a3158bada(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>5 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT id, timestamp, event_data FROM public.events WHERE app_name = (params->>0)::text AND user_id = (params->>1)::text AND session_id = (params->>2)::text ORDER BY timestamp ASC, id ASC OFFSET (params->>3)::int8 LIMIT (params->>4)::int8) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_6a10b8fa3f5a3158bada(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1100
CREATE OR REPLACE FUNCTION carousel_internal.q_eabfe4448197a58cbb86(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>1 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT max(seq) FROM run_events WHERE run_id = (params->>0)::text) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_eabfe4448197a58cbb86(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1261
CREATE OR REPLACE FUNCTION carousel_internal.q_70c166007442d779103b(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>5 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT md5(COALESCE(string_agg(id || ':' || revision, ',' ORDER BY timestamp, id), '')) FROM (SELECT id, timestamp, xmin::text AS revision FROM public.events WHERE app_name=(params->>0)::text AND user_id=(params->>1)::text AND session_id=(params->>2)::text ORDER BY timestamp ASC, id ASC OFFSET (params->>3)::int8 LIMIT (params->>4)::int8) page) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_70c166007442d779103b(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1515
CREATE OR REPLACE FUNCTION carousel_internal.q_d59cf7928a56d20c71ac(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>2 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT payload FROM carousel_designs WHERE owner_email = (params->>0)::text AND design_id = (params->>1)::text) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_d59cf7928a56d20c71ac(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1500
CREATE OR REPLACE FUNCTION carousel_internal.q_bb94dad8ae7c419f7687(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>1 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT payload FROM carousel_designs WHERE owner_email = (params->>0)::text ORDER BY sort_order ASC, created_at ASC) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_bb94dad8ae7c419f7687(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:510
CREATE OR REPLACE FUNCTION carousel_internal.q_545645d7eb0642052cab(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>1 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT run_id, session_id, function_call_id, created_at FROM pending_reviews WHERE run_id = (params->>0)::text) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_545645d7eb0642052cab(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.memory_service:370
CREATE OR REPLACE FUNCTION carousel_internal.q_ce6046ffb243baec4ef3(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>1 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT run_id, verdict, feedback, targets, news_title, created_at FROM feedback ORDER BY created_at DESC LIMIT (params->>0)::int8) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_ce6046ffb243baec4ef3(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1069
CREATE OR REPLACE FUNCTION carousel_internal.q_f9daf15692827e28202e(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>4 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT seq, kind, author, text, data, created_at FROM run_events WHERE run_id = (params->>0)::text AND seq > (params->>1)::int4 AND (NOT (params->>3)::bool::boolean OR (kind IN ('terminal', 'error') AND btrim(COALESCE(author, '')) = '')) ORDER BY seq ASC LIMIT (params->>2)::int8) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_f9daf15692827e28202e(jsonb) FROM PUBLIC,anon,authenticated;

-- app.review.verdict:99
CREATE OR REPLACE FUNCTION carousel_internal.q_5ce60c9f1a7635fffcb1(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>3 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT state FROM sessions WHERE app_name = (params->>0)::text AND user_id = (params->>1)::text AND id = (params->>2)::text) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_5ce60c9f1a7635fffcb1(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1120
CREATE OR REPLACE FUNCTION carousel_internal.q_0b42d4053d8d27e6d58c(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>1 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (SELECT value FROM app_config WHERE key = (params->>0)::text) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_0b42d4053d8d27e6d58c(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1452
CREATE OR REPLACE FUNCTION carousel_internal.q_2049aaac51f7e0887d2f(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>1 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; UPDATE instagram_accounts SET is_default = (id = (params->>0)::text); GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_2049aaac51f7e0887d2f(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1432
CREATE OR REPLACE FUNCTION carousel_internal.q_7e9bd40f96dfe13c5080(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>3 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; UPDATE instagram_accounts SET token_enc = (params->>1)::text, token_expires_at = (params->>2)::timestamptz, last_refreshed_at = now() WHERE id = (params->>0)::text; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_7e9bd40f96dfe13c5080(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:235
CREATE OR REPLACE FUNCTION carousel_internal.q_c8f0f3d9d0796570cb63(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>3 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (UPDATE news_queue SET payload = '{}'::jsonb, status = (params->>1)::text WHERE id = (params->>0)::text AND status = (params->>2)::text AND NOT EXISTS (SELECT 1 FROM runs WHERE news_id = (params->>0)::text) RETURNING id) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_c8f0f3d9d0796570cb63(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:140
CREATE OR REPLACE FUNCTION carousel_internal.q_144a68a60b04847b8fff(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>3 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; UPDATE news_queue SET payload = jsonb_set(payload, '{thumbnail_url}', to_jsonb((params->>1)::text::text)) WHERE id = (params->>0)::text AND status = (params->>2)::text AND COALESCE(payload->>'thumbnail_url', '') = ''; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_144a68a60b04847b8fff(jsonb) FROM PUBLIC,anon,authenticated;

-- app.runs.recovery:105
CREATE OR REPLACE FUNCTION carousel_internal.q_3205d58b34562cf9e2ec(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>3 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (UPDATE news_queue SET status = (params->>0)::text WHERE status = (params->>1)::text AND NOT EXISTS ( SELECT 1 FROM runs r WHERE r.news_id = news_queue.id AND r.status = ANY((CASE WHEN params->2='null'::jsonb THEN NULL ELSE ARRAY(SELECT jsonb_array_elements_text(params->2))::text[] END)::text[]) ) RETURNING id) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_3205d58b34562cf9e2ec(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:344
CREATE OR REPLACE FUNCTION carousel_internal.q_22b46c72c050b2206f98(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>2 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; UPDATE news_queue SET status = (params->>1)::text WHERE id = (params->>0)::text; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_22b46c72c050b2206f98(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:322
CREATE OR REPLACE FUNCTION carousel_internal.q_4354c21ea1f5c20f6906(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>3 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (UPDATE news_queue SET status = (params->>1)::text WHERE id = (params->>0)::text AND status = (params->>2)::text RETURNING id) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_4354c21ea1f5c20f6906(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:261
CREATE OR REPLACE FUNCTION carousel_internal.q_7d4c661546af06a2bf54(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>3 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (UPDATE news_queue SET status = (params->>1)::text WHERE id = (params->>0)::text AND status = (params->>2)::text RETURNING id, payload) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_7d4c661546af06a2bf54(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:294
CREATE OR REPLACE FUNCTION carousel_internal.q_22db42828c603cf66478(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>3 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (UPDATE news_queue SET status = (params->>1)::text WHERE url_hash = (params->>0)::text AND status = (params->>2)::text RETURNING id) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_22db42828c603cf66478(jsonb) FROM PUBLIC,anon,authenticated;

-- web_api.routes_runs:796
CREATE OR REPLACE FUNCTION carousel_internal.q_31360ef474d265b02e32(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>5 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; UPDATE public.sessions SET state = jsonb_set(CASE WHEN jsonb_typeof(state)='string' THEN (state #>> '{}')::jsonb ELSE COALESCE(state,'{}'::jsonb) END, ARRAY[(params->>4)::text::text], (params->3)::jsonb::jsonb), update_time = now() WHERE app_name = (params->>0)::text AND user_id = (params->>1)::text AND id = (params->>2)::text; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_31360ef474d265b02e32(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1466
CREATE OR REPLACE FUNCTION carousel_internal.q_7e6b9ea7526f4e28b446(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>2 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; UPDATE runs SET account_id = (params->>1)::text, updated_at = now() WHERE run_id = (params->>0)::text; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_7e6b9ea7526f4e28b446(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:430
CREATE OR REPLACE FUNCTION carousel_internal.q_ebfd36b970cef723b705(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>4 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; UPDATE runs SET phase = (params->>1)::text, status = (params->>2)::text, review_round = (params->>3)::int4, updated_at = now() WHERE run_id = (params->>0)::text; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_ebfd36b970cef723b705(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:420
CREATE OR REPLACE FUNCTION carousel_internal.q_f1236027540e78157c02(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>3 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; UPDATE runs SET phase = (params->>1)::text, status = (params->>2)::text, updated_at = now() WHERE run_id = (params->>0)::text; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_f1236027540e78157c02(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:755
CREATE OR REPLACE FUNCTION carousel_internal.q_78672084dee3b3f3f666(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>2 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; UPDATE runs SET status = (params->>1)::text, updated_at = now() WHERE run_id = (params->>0)::text; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_78672084dee3b3f3f666(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:738
CREATE OR REPLACE FUNCTION carousel_internal.q_387a5d2172323f7ee565(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>2 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; UPDATE runs SET title = (params->>1)::text WHERE run_id = (params->>0)::text AND NOT title_locked; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_387a5d2172323f7ee565(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:669
CREATE OR REPLACE FUNCTION carousel_internal.q_5f85587cea0e02fb38d3(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>4 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; UPDATE runs SET title = COALESCE(NULLIF((params->>1)::text, ''), title), source = COALESCE(NULLIF((params->>2)::text, ''), source), requested_by = COALESCE(NULLIF((params->>3)::text, ''), requested_by), updated_at = now() WHERE run_id = (params->>0)::text; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_5f85587cea0e02fb38d3(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:706
CREATE OR REPLACE FUNCTION carousel_internal.q_5c53db56592c1a9ea6f4(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>2 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; UPDATE runs SET title = NULLIF((params->>1)::text, ''), title_locked = true WHERE run_id = (params->>0)::text; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_5c53db56592c1a9ea6f4(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:777
CREATE OR REPLACE FUNCTION carousel_internal.q_5913150d4367ae1cc498(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>1 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; UPDATE runs SET updated_at = now() WHERE run_id = (params->>0)::text; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected); RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_5913150d4367ae1cc498(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:1008
CREATE OR REPLACE FUNCTION carousel_internal.q_41c2a8fa77c0888aaddc(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>4 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (UPDATE sessions SET state = jsonb_set( COALESCE(state, '{}'::jsonb), '{review_verdict}', (params->3)::jsonb::jsonb, true ), update_time = now() WHERE app_name = (params->>0)::text AND user_id = (params->>1)::text AND id = (params->>2)::text AND COALESCE(state -> 'review_verdict', 'null'::jsonb) = 'null'::jsonb RETURNING id) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_41c2a8fa77c0888aaddc(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:949
CREATE OR REPLACE FUNCTION carousel_internal.q_77ebda89c22e8ff6abca(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>4 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (UPDATE sessions SET state = jsonb_set( jsonb_set( jsonb_set( COALESCE(state, '{}'::jsonb), '{rework_round}', '0'::jsonb, true ), '{qa_round}', '0'::jsonb, true ), '{phase}', to_jsonb((params->>3)::text::text), true ), update_time = now() WHERE app_name = (params->>0)::text AND user_id = (params->>1)::text AND id = (params->>2)::text RETURNING id) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_77ebda89c22e8ff6abca(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:165
CREATE OR REPLACE FUNCTION carousel_internal.q_fc8dc8d7270214e12388(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>2 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (WITH next AS ( SELECT id FROM news_queue WHERE status = (params->>0)::text ORDER BY created_at ASC FOR UPDATE SKIP LOCKED LIMIT 1 ) UPDATE news_queue q SET status = (params->>1)::text FROM next WHERE q.id = next.id RETURNING q.id, q.payload) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_fc8dc8d7270214e12388(jsonb) FROM PUBLIC,anon,authenticated;

-- app.services.db:843
CREATE OR REPLACE FUNCTION carousel_internal.q_99ec7d2f1c8bd3068157(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>5 THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF; WITH result AS (WITH recent AS ( SELECT status FROM runs ORDER BY created_at DESC LIMIT 50 ) SELECT count(*) FILTER (WHERE status = (params->>0)::text) AS running, count(*) FILTER (WHERE status = (params->>1)::text) AS awaiting_review, count(*) FILTER (WHERE status IN ((params->>2)::text, (params->>3)::text)) AS stopped, (SELECT count(*) FROM news_queue WHERE status = (params->>4)::text) AS queued FROM recent) SELECT jsonb_build_object('rows',COALESCE(jsonb_agg(to_jsonb(result)),'[]'::jsonb),'count',count(*)) INTO output FROM result; RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.q_99ec7d2f1c8bd3068157(jsonb) FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION public.carousel_query(operation text, params jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $rpc$
BEGIN CASE operation
WHEN 'q_66d6ec24b25d3ac190dc' THEN RETURN carousel_internal.q_66d6ec24b25d3ac190dc(params);
WHEN 'q_db06a33199c9486804a6' THEN RETURN carousel_internal.q_db06a33199c9486804a6(params);
WHEN 'q_b9f11b639815277496d7' THEN RETURN carousel_internal.q_b9f11b639815277496d7(params);
WHEN 'q_c7ccaf1d349ca9c0b1a8' THEN RETURN carousel_internal.q_c7ccaf1d349ca9c0b1a8(params);
WHEN 'q_b9eb5873954e0c5ddb20' THEN RETURN carousel_internal.q_b9eb5873954e0c5ddb20(params);
WHEN 'q_31b15702d6e871ae9ea7' THEN RETURN carousel_internal.q_31b15702d6e871ae9ea7(params);
WHEN 'q_8dd89723936f1007a918' THEN RETURN carousel_internal.q_8dd89723936f1007a918(params);
WHEN 'q_8221394f0d0a06bc0067' THEN RETURN carousel_internal.q_8221394f0d0a06bc0067(params);
WHEN 'q_257f54c3425331ee9258' THEN RETURN carousel_internal.q_257f54c3425331ee9258(params);
WHEN 'q_5f15232ef02472dda91c' THEN RETURN carousel_internal.q_5f15232ef02472dda91c(params);
WHEN 'q_5703021faed72a1fc5ea' THEN RETURN carousel_internal.q_5703021faed72a1fc5ea(params);
WHEN 'q_39816ede3cb98f6fa805' THEN RETURN carousel_internal.q_39816ede3cb98f6fa805(params);
WHEN 'q_142f5eb3b635be7999e6' THEN RETURN carousel_internal.q_142f5eb3b635be7999e6(params);
WHEN 'q_81d29b5a1246b41abffa' THEN RETURN carousel_internal.q_81d29b5a1246b41abffa(params);
WHEN 'q_d01506a7a95cb13ae4a6' THEN RETURN carousel_internal.q_d01506a7a95cb13ae4a6(params);
WHEN 'q_494f276d0c2e73072b8e' THEN RETURN carousel_internal.q_494f276d0c2e73072b8e(params);
WHEN 'q_01773445dea14a19d433' THEN RETURN carousel_internal.q_01773445dea14a19d433(params);
WHEN 'q_b15c77692c7f308c6c33' THEN RETURN carousel_internal.q_b15c77692c7f308c6c33(params);
WHEN 'q_edc732ff5423b6c65644' THEN RETURN carousel_internal.q_edc732ff5423b6c65644(params);
WHEN 'q_d5878fa1b98bfc26a50b' THEN RETURN carousel_internal.q_d5878fa1b98bfc26a50b(params);
WHEN 'q_f2fa2c19619b8853c24c' THEN RETURN carousel_internal.q_f2fa2c19619b8853c24c(params);
WHEN 'q_e263c30765e201849caa' THEN RETURN carousel_internal.q_e263c30765e201849caa(params);
WHEN 'q_b337d4a5a13f14e7f3c1' THEN RETURN carousel_internal.q_b337d4a5a13f14e7f3c1(params);
WHEN 'q_c0445461a72264308f2b' THEN RETURN carousel_internal.q_c0445461a72264308f2b(params);
WHEN 'q_538c2d6dde84e4ab4e0f' THEN RETURN carousel_internal.q_538c2d6dde84e4ab4e0f(params);
WHEN 'q_b6f610789162c99e43ef' THEN RETURN carousel_internal.q_b6f610789162c99e43ef(params);
WHEN 'q_793e6c2b2cae23805dbb' THEN RETURN carousel_internal.q_793e6c2b2cae23805dbb(params);
WHEN 'q_dcf939d0ed39e5939414' THEN RETURN carousel_internal.q_dcf939d0ed39e5939414(params);
WHEN 'q_1278e6f6628786a1cee6' THEN RETURN carousel_internal.q_1278e6f6628786a1cee6(params);
WHEN 'q_8d6a6ed71afeda6dd765' THEN RETURN carousel_internal.q_8d6a6ed71afeda6dd765(params);
WHEN 'q_6a10b8fa3f5a3158bada' THEN RETURN carousel_internal.q_6a10b8fa3f5a3158bada(params);
WHEN 'q_eabfe4448197a58cbb86' THEN RETURN carousel_internal.q_eabfe4448197a58cbb86(params);
WHEN 'q_70c166007442d779103b' THEN RETURN carousel_internal.q_70c166007442d779103b(params);
WHEN 'q_d59cf7928a56d20c71ac' THEN RETURN carousel_internal.q_d59cf7928a56d20c71ac(params);
WHEN 'q_bb94dad8ae7c419f7687' THEN RETURN carousel_internal.q_bb94dad8ae7c419f7687(params);
WHEN 'q_545645d7eb0642052cab' THEN RETURN carousel_internal.q_545645d7eb0642052cab(params);
WHEN 'q_ce6046ffb243baec4ef3' THEN RETURN carousel_internal.q_ce6046ffb243baec4ef3(params);
WHEN 'q_f9daf15692827e28202e' THEN RETURN carousel_internal.q_f9daf15692827e28202e(params);
WHEN 'q_5ce60c9f1a7635fffcb1' THEN RETURN carousel_internal.q_5ce60c9f1a7635fffcb1(params);
WHEN 'q_0b42d4053d8d27e6d58c' THEN RETURN carousel_internal.q_0b42d4053d8d27e6d58c(params);
WHEN 'q_2049aaac51f7e0887d2f' THEN RETURN carousel_internal.q_2049aaac51f7e0887d2f(params);
WHEN 'q_7e9bd40f96dfe13c5080' THEN RETURN carousel_internal.q_7e9bd40f96dfe13c5080(params);
WHEN 'q_c8f0f3d9d0796570cb63' THEN RETURN carousel_internal.q_c8f0f3d9d0796570cb63(params);
WHEN 'q_144a68a60b04847b8fff' THEN RETURN carousel_internal.q_144a68a60b04847b8fff(params);
WHEN 'q_3205d58b34562cf9e2ec' THEN RETURN carousel_internal.q_3205d58b34562cf9e2ec(params);
WHEN 'q_22b46c72c050b2206f98' THEN RETURN carousel_internal.q_22b46c72c050b2206f98(params);
WHEN 'q_4354c21ea1f5c20f6906' THEN RETURN carousel_internal.q_4354c21ea1f5c20f6906(params);
WHEN 'q_7d4c661546af06a2bf54' THEN RETURN carousel_internal.q_7d4c661546af06a2bf54(params);
WHEN 'q_22db42828c603cf66478' THEN RETURN carousel_internal.q_22db42828c603cf66478(params);
WHEN 'q_31360ef474d265b02e32' THEN RETURN carousel_internal.q_31360ef474d265b02e32(params);
WHEN 'q_7e6b9ea7526f4e28b446' THEN RETURN carousel_internal.q_7e6b9ea7526f4e28b446(params);
WHEN 'q_ebfd36b970cef723b705' THEN RETURN carousel_internal.q_ebfd36b970cef723b705(params);
WHEN 'q_f1236027540e78157c02' THEN RETURN carousel_internal.q_f1236027540e78157c02(params);
WHEN 'q_78672084dee3b3f3f666' THEN RETURN carousel_internal.q_78672084dee3b3f3f666(params);
WHEN 'q_387a5d2172323f7ee565' THEN RETURN carousel_internal.q_387a5d2172323f7ee565(params);
WHEN 'q_5f85587cea0e02fb38d3' THEN RETURN carousel_internal.q_5f85587cea0e02fb38d3(params);
WHEN 'q_5c53db56592c1a9ea6f4' THEN RETURN carousel_internal.q_5c53db56592c1a9ea6f4(params);
WHEN 'q_5913150d4367ae1cc498' THEN RETURN carousel_internal.q_5913150d4367ae1cc498(params);
WHEN 'q_41c2a8fa77c0888aaddc' THEN RETURN carousel_internal.q_41c2a8fa77c0888aaddc(params);
WHEN 'q_77ebda89c22e8ff6abca' THEN RETURN carousel_internal.q_77ebda89c22e8ff6abca(params);
WHEN 'q_fc8dc8d7270214e12388' THEN RETURN carousel_internal.q_fc8dc8d7270214e12388(params);
WHEN 'q_99ec7d2f1c8bd3068157' THEN RETURN carousel_internal.q_99ec7d2f1c8bd3068157(params);
ELSE RAISE EXCEPTION 'Unknown database operation'; END CASE; END $rpc$;
REVOKE ALL ON FUNCTION public.carousel_query(text,jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.carousel_query(text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.carousel_query_batch(operation text, batches jsonb) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $rpc$
DECLARE args jsonb;
BEGIN
 IF jsonb_typeof(batches) IS DISTINCT FROM 'array' THEN RAISE EXCEPTION 'Invalid batches'; END IF;
 FOR args IN SELECT value FROM jsonb_array_elements(batches) LOOP
  PERFORM public.carousel_query(operation,args);
 END LOOP;
END $rpc$;
REVOKE ALL ON FUNCTION public.carousel_query_batch(text,jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.carousel_query_batch(text,jsonb) TO service_role;
NOTIFY pgrst,'reload schema';
COMMIT;
