"""Free reference photos of the story's people, organisation and places.

When every picture found on the story's own pages was rejected, the cover
used to fall straight to a plain drawn background with the title on it. This
module is the free rung in between: Wikidata names the photo that illustrates
each subject (its P18 image, and the photo of an organisation's CEO, chair or
founder), and Wikimedia Commons serves that file under a free licence with an
author to credit.

No key and no billing: two public APIs over plain GETs, with a time budget.
Every file is checked before it is offered. AI-generated art, logos, flags,
maps, charts and screenshots are dropped, and so are files too small for a
1080x1350 cover and anything not on the licence allowlist (public domain,
CC BY, OGL; CC BY-SA only when ``settings.cover_allow_share_alike`` is on).
Nothing here raises: a failed lookup offers nothing.

The same Wikidata items also name each subject's official website (P856),
which tells the cover judge a company's own pages from fan sites
(:func:`official_sites`), and :func:`file_credit` credits a Wikimedia file
the cover found some other way.
"""
from __future__ import annotations

import html
import logging
import re
import time
import unicodedata
from collections import Counter
from collections.abc import Mapping, Sequence
from concurrent.futures import ThreadPoolExecutor
from typing import Any, Optional
from urllib.parse import quote, unquote, urlparse

import requests

from app.config import settings
from app.text_rules import require_no_em_dash, require_readable_text, straight_quotes
from app.tools import media_tools

logger = logging.getLogger(__name__)

_WIKIDATA_API = "https://www.wikidata.org/w/api.php"
_COMMONS_API = "https://commons.wikimedia.org/w/api.php"
# (connect, read), cut further by what is left of the budget. At (10, 20) with
# a retry, one subject's lookups took 11-20 s and a slow API about six minutes.
_TIMEOUT = (5, 10)
_ATTEMPTS = 2  # one retry per request, and only while this much budget is left:
_RETRY_MIN_S = 10.0
_MIN_REQUEST_S = 0.5  # below this much budget a request is not worth starting
_MAX_SUBJECTS = 4
_ENTITY_HITS = 5
_SUBJECT_FILES = 3  # P18 files read per entity; most have one, a leader a few
_LEADER_PROPS = ("P169", "P488", "P112")  # chief executive, chairperson, founder
_MAX_LEADERS = 2
_SEARCH_LIMIT = 8
# A keyword search is noisier than a curated Wikidata image, so one subject's
# search results never crowd out the next subject's own photo.
_SEARCH_KEEP = 3
# At most this many photos per subject, taken in turns: with the subjects in
# order, the first one's weak files filled all six slots ("Mistral Small"
# found a flower show, a mountain and an electrical panel).
_PER_SUBJECT = 2
# A namesake that is no person, body or place must share this many words
# with the story to count as the one it means.
_MIN_SHARED_WORDS = 2
# The Wikidata lookups of the subjects run side by side; one after another
# they took about 20 of a 40-second budget.
_WORKERS = 4
_THUMB_WIDTH = 1920
_CREDIT_MAX = 80
# CC BY-SA photos may be reused, but the carousel then carries a share-alike
# licence obligation. The owner has not decided, so they are off by default
# (COVER_ALLOW_SHARE_ALIKE) and rank last when on.
_ALLOW_SHARE_ALIKE = settings.cover_allow_share_alike
# CC BY asks for changes to be indicated; the cover crops the photo and lays
# the headline over it.
_CHANGES_NOTE = "(cropped, text added)"
_ROLE_ORDER = {"subject": 0, "leader": 1, "search": 2}
_ROLE_SCORE = {"subject": 60, "leader": 54, "search": 46}
_MIMES = frozenset({"image/jpeg", "image/png", "image/webp", "image/tiff"})
# A keyword search's PNGs and WebPs were diagrams, UI captures and renders;
# photos on Commons are JPEGs.
_SEARCH_MIMES = frozenset({"image/jpeg"})
_METADATA_FIELDS = "LicenseShortName|Artist|Categories|NonFree"
_IMAGE_INFO = {
    "prop": "imageinfo|categories",
    "iiprop": "url|size|mime|extmetadata",
    "iiurlwidth": str(_THUMB_WIDTH),
    "iiextmetadatafilter": _METADATA_FIELDS,
    "cllimit": "50",
}
# Commons files AI tools made. 'Mistral AI representation (FLUX Pro).webp' is
# in "Images generated by Flux (text-to-image model)" and tagged PD-algorithm.
_AI_CATEGORY_RE = re.compile(
    r"AI-generated|generated by|PD-algorithm|text-to-image|midjourney"
    r"|(?<![a-z])dall[-_ \u00b7.]?e(?![a-z])|stable diffusion|(?<![a-z])flux(?![a-z])",
    re.I,
)
# File names of pictures that show no person, place or thing to put on a cover.
_NOT_A_PHOTO_RE = re.compile(
    r"\b(?:logos?|flags?|coats? of arms|maps?|charts?|graphs?|diagrams?|signatures?"
    r"|seals?|approval ratings?|screenshots?|icons?)\b",
    re.I,
)
# Wikidata items that are a name or a paper, not the person or company
# carrying it ("UltraSpeed" found only 1970s dental articles).
_NOT_AN_ENTITY_RE = re.compile(
    r"family name|given name|surname|disambiguation|Wikimedia (?:list|category)"
    r"|(?:scientific|scholarly) article",
    re.I,
)
# When a word is the exact label of several items ("Mistral": a warship, a
# submarine, a program), the one a news story means is a person or a body.
_STORY_ENTITY_RE = re.compile(
    r"company|corporation|organi[sz]ation|agency|government|department|ministry|startup"
    r"|brand|manufacturer|laboratory|university|politician|minister|president|businessperson"
    r"|business(?:man|woman)|investor|executive|entrepreneur|founder|engineer|scientist"
    r"|city|country|state",
    re.I,
)
# The licence allowlist. Anything else is left out: NC, ND and fair use, but
# also GFDL, GPL and the Free Art License, whose terms ask for the whole
# licence text or a copyleft the post cannot carry.
_NO_REUSE_RE = re.compile(r"fair use|non-?free|non-?commercial|no-?deriv", re.I)
_NC_ND_RE = re.compile(r"\bN[CD]\b")
_VERSION = r"(?:[ -]?\d(?:\.\d)?)?(?:[ -](?:[a-z]{2}|igo))?"
_PUBLIC_DOMAIN_RE = re.compile(r"^(?:cc0(?: 1\.0)?|cc-zero|public domain\b.*|pd(?:-[\w-]+)?)$", re.I)
_ATTRIBUTION_RE = re.compile(
    rf"^(?:cc[- ]by{_VERSION}|attribution|ogl(?:[ -]?v?\d(?:\.\d)?)?|godl(?:-india)?"
    r"|copyrighted free use)$",
    re.I,
)
_SHARE_ALIKE_RE = re.compile(rf"^cc[- ]by[- ]sa{_VERSION}$", re.I)
_TAG_RE = re.compile(r"<[^>]+>")
_DASHES = str.maketrans({"\u2014": "-", "\u2013": "-", "\u2012": "-", "\u2010": "-", "\u2011": "-"})

# --- story_subjects ----------------------------------------------------------

# A line shorter than this is page furniture (menus, bylines, headings) when
# the news summary is a scraped page, as BBC's was.
_MIN_PROSE_WORDS = 6
_FACTS_READ = 12
_MAX_NAME_WORDS = 5
_SHOUTED_RUN = 3  # this many all-caps words in a row are a shouted headline
_WORD_RE = re.compile(r"[A-Za-z][A-Za-z0-9]*")
# Punctuation and spaced dashes end a name; a line break does too.
_NAME_BREAK_RE = re.compile(r"[,.;:!?()\[\]{}\"|/\n]+|\s-\s")
_POSSESSIVE_RE = re.compile("['\u2019]s?$")
# Capitalised words that do not name the story's subject: months, weekdays,
# sentence starters, job titles and the menu words of a scraped news page.
_STOPWORDS = frozenset(
    """
    january february march april may june july august september october november december
    jan feb mar apr jun jul aug sep sept oct nov dec
    monday tuesday wednesday thursday friday saturday sunday
    the this that these those there here then than what when where which who whom whose why how
    and but for nor yet with without from into onto over under after before during since until
    while about above across against along among around because although though however
    meanwhile moreover also according despite unlike like plus via per its his her hers their
    theirs our ours your yours she they them we you not now new news today tonight yesterday
    tomorrow last next first second third one two three four five more most some many all any
    each every other another such only just even still will would can could should might must
    has have had was were are did does done being been said says say see watch read share save
    skip home live video videos sport sports business technology tech health culture arts
    travel earth audio weather newsletters newsletter world standard official breaking update
    updates exclusive report reports week weekend month year years day days minister prime
    president chief executive officer ceo cto cfo coo senator premier secretary chairman chair
    founder director mr mrs ms dr sir professor prof hon
    api apis llm llms gpu gpus cpu sdk pdf url faq usd aud eur gbp utc gmt est pst
    inc ltd llc plc corp co add ago ends
    """.split()
)
# A nationality starts a name ('Australian Signals Directorate') but never
# continues one: 'an OpenAI Australian government hack' names two things.
_DEMONYMS = frozenset(
    """
    african american asian australian brazilian british canadian chinese dutch emirati
    english european french german indian iranian irish israeli italian japanese korean
    mexican russian saudi scottish singaporean spanish swedish swiss taiwanese turkish
    ukrainian welsh
    """.split()
)


def _meta(meta: Mapping, key: str) -> str:
    value = meta.get(key)
    if isinstance(value, Mapping):
        value = value.get("value")
    return str(value or "")


def _plain(text: str) -> str:
    """Commons HTML (an Artist field) as one short line of plain house-style text."""
    text = html.unescape(_TAG_RE.sub(" ", str(text or "")))
    text = straight_quotes(text.translate(_DASHES))
    text = " ".join(text.split())
    if len(text) > _CREDIT_MAX:
        cut = text[:_CREDIT_MAX]
        text = (cut.rsplit(" ", 1)[0] if " " in cut else cut).rstrip(" ,;:-/(")
    return text


def _publishable(text: str) -> bool:
    try:
        require_no_em_dash(text, "credit")
        require_readable_text(text, "credit")
    except ValueError:
        return False
    return True


def _credit(artist_html: str, licence: str) -> str:
    """'<Artist> / Wikimedia Commons, <licence>', or '' when nothing passes the text rules.

    An attribution licence gets :data:`_CHANGES_NOTE`: CC BY asks for
    changes to be indicated, and the cover crops the photo and adds text.
    """
    artist = _plain(artist_html)
    note = "" if _licence_class(licence) == 0 else f" {_CHANGES_NOTE}"
    for credit in (
        f"{artist} / Wikimedia Commons, {licence}{note}" if artist else "",
        f"Wikimedia Commons, {licence}{note}",
    ):
        if credit and _publishable(credit):
            return credit
    return ""


def _licence_class(licence: str) -> Optional[int]:
    """0 public domain, 1 attribution only, 2 share-alike; None when not on the allowlist."""
    text = " ".join(str(licence or "").split())
    if not text or _NO_REUSE_RE.search(text) or _NC_ND_RE.search(text):
        return None
    if _PUBLIC_DOMAIN_RE.match(text):
        return 0
    if _SHARE_ALIKE_RE.match(text):
        return 2
    if _ATTRIBUTION_RE.match(text):
        return 1
    # An unrecognised licence is not known to be free: leave it out.
    return None


def _licence_rank(licence: str, allow_share_alike: Optional[bool] = None) -> Optional[int]:
    """:func:`_licence_class`, with share-alike refused unless it is switched on."""
    rank = _licence_class(licence)
    allowed = _ALLOW_SHARE_ALIKE if allow_share_alike is None else allow_share_alike
    if rank == 2 and not allowed:
        return None
    return rank


class _Api:
    """GETs against the two APIs within one overall time budget.

    A request that fails twice, or does not fit in what is left of the
    budget, returns None and that step is skipped.
    """

    def __init__(self, session: Any, budget_s: float) -> None:
        self.session = session
        self.deadline = time.monotonic() + max(float(budget_s), 0.0)

    def get(self, url: str, params: dict) -> Optional[dict]:
        for attempt in range(_ATTEMPTS):
            left = self.deadline - time.monotonic()
            if left < _MIN_REQUEST_S or (attempt and left < _RETRY_MIN_S):
                return None
            try:
                response = self.session.get(
                    url,
                    params=params,
                    headers={"User-Agent": media_tools.WIKIMEDIA_USER_AGENT},
                    timeout=(min(_TIMEOUT[0], left), min(_TIMEOUT[1], left)),
                )
                response.raise_for_status()
                data = response.json()
                return data if isinstance(data, dict) else None
            except (requests.RequestException, ValueError) as exc:
                logger.info("Wikimedia request failed (%s %s): %s", url, params.get("action"), exc)
        return None


def _statements(claims: Mapping, prop: str) -> list[Any]:
    """Values of one property, preferred rank first, no deprecated or ended ones."""
    ranked: list[tuple[int, Any]] = []
    for statement in claims.get(prop) or []:
        rank = statement.get("rank")
        # A former CEO keeps the claim with an end time (P582); skip it.
        if rank == "deprecated" or "P582" in (statement.get("qualifiers") or {}):
            continue
        value = ((statement.get("mainsnak") or {}).get("datavalue") or {}).get("value")
        if isinstance(value, Mapping):
            value = value.get("id")
        if value:
            ranked.append((0 if rank == "preferred" else 1, value))
    ranked.sort(key=lambda item: item[0])
    seen: list[Any] = []
    for _rank, value in ranked:
        if value not in seen:
            seen.append(value)
    return seen


def _fold(text: str) -> str:
    """Case- and accent-free text: 'Clément' and 'clement' compare equal."""
    decomposed = unicodedata.normalize("NFKD", str(text or ""))
    return "".join(ch for ch in decomposed if not unicodedata.combining(ch)).casefold()


def _context_words(text: str) -> set[str]:
    """The story's words of four letters or more, for telling namesakes apart."""
    return {word for word in re.findall(r"[a-z]{4,}", _fold(text)) if word not in _STOPWORDS}


def _entity(api: _Api, subject: str, context: frozenset[str] = frozenset()) -> tuple[str, bool, str]:
    """The Wikidata item a subject names: (id, person/body/place, description).

    Only an item whose label or alias IS the subject counts; the first hit of
    a search that has none ("Medicare Statistics Reporting Service Portal",
    "UltraSpeed") is somebody else. Among exact namesakes the one whose
    description shares words with the story wins ("Medicare": Australia's
    scheme over the US programme), and one that is neither a person or body
    nor about the story (a warship, a radio technique) offers nothing.
    """
    data = api.get(_WIKIDATA_API, {
        "action": "wbsearchentities", "search": subject, "language": "en", "uselang": "en",
        "type": "item", "limit": str(_ENTITY_HITS), "format": "json",
    }) or {}
    hits = [
        hit for hit in data.get("search") or []
        if hit.get("id") and not _NOT_AN_ENTITY_RE.search(str(hit.get("description") or ""))
    ]
    wanted = _fold(subject)
    exact = [
        hit for hit in hits
        if any(
            _fold(name) == wanted
            for name in [str(hit.get("label") or "")] + [str(a) for a in hit.get("aliases") or []]
        )
    ]

    # The subject's own words say nothing: "2004 Mistral-class amphibious
    # assault ship" shares "mistral" with every Mistral story.
    own = _context_words(subject)

    def fit(hit: dict) -> tuple[int, bool]:
        description = str(hit.get("description") or "")
        return (
            len((_context_words(description) - own) & context),
            bool(_STORY_ENTITY_RE.search(description)),
        )

    ranked = sorted(exact, key=fit, reverse=True)
    if not ranked:
        return "", False, ""
    hit = ranked[0]
    shared, placed = fit(hit)
    # The story tells namesakes apart when one shares more of its words than
    # every other ("Medicare": Australia's scheme over the US programme).
    singled_out = shared >= 1 and all(fit(other)[0] < shared for other in ranked[1:])
    if not (placed or shared >= _MIN_SHARED_WORDS or (len(ranked) > 1 and singled_out)):
        return "", False, ""
    description = " ".join(str(hit.get("description") or "").split())
    return str(hit["id"]), placed, description


def _entities(api: _Api, ids: Sequence[str], props: str) -> dict:
    params = {"action": "wbgetentities", "ids": "|".join(ids), "props": props, "format": "json"}
    if "labels" in props:
        params["languages"] = "en"
    data = api.get(_WIKIDATA_API, params) or {}
    entities = data.get("entities")
    return entities if isinstance(entities, dict) else {}


def _wanted_files(
    api: _Api, index: int, subject: str, context: frozenset[str] = frozenset(),
) -> tuple[list[tuple[int, str, str, str, int, str, str]], bool]:
    """The files one subject's Wikidata item names, and whether it was placed.

    Each entry is (subject index, role, file name, who it shows, leader
    position, what the picture is about, the leader's item id). "Placed"
    means Wikidata knows the subject as a person, body or place, which lets
    a one-word subject fall back to a Commons search.
    """
    entity_id, placed, description = _entity(api, subject, context)
    if not entity_id:
        return [], placed
    about = f"{subject}: {description}" if description else subject
    entities = _entities(api, [entity_id], "claims")
    # A merged item answers under the id it was merged into.
    entity = entities.get(entity_id) or (next(iter(entities.values())) if len(entities) == 1 else {})
    claims = (entity or {}).get("claims") or {}
    wanted = [
        (index, "subject", name, subject, 0, about, "")
        for name in _statements(claims, "P18")[:_SUBJECT_FILES]
    ]
    leaders: list[str] = []
    for prop in _LEADER_PROPS:
        for person in _statements(claims, prop):
            if person not in leaders and person != entity_id:
                leaders.append(person)
    leaders = leaders[:_MAX_LEADERS]
    if leaders:
        people = _entities(api, leaders, "claims|labels")
        for position, person in enumerate(leaders):
            entity = people.get(person) or {}
            files = _statements(entity.get("claims") or {}, "P18")
            label = str(((entity.get("labels") or {}).get("en") or {}).get("value") or "")
            if files:
                who = label or subject
                wanted.append((
                    index, "leader", files[0], who, position,
                    f"{who}, a leader or founder of {about}", person,
                ))
    return wanted, placed


def _commons_pages(api: _Api, names: Sequence[str]) -> dict[str, dict]:
    """Commons pages for P18 file names, keyed by the name as Wikidata gave it."""
    titles = list(dict.fromkeys(f"File:{name}" for name in names))
    if not titles:
        return {}
    data = api.get(_COMMONS_API, {
        "action": "query", "format": "json", "formatversion": "2",
        "titles": "|".join(titles), **_IMAGE_INFO,
    }) or {}
    query = data.get("query") or {}
    renamed = {str(n.get("from")): str(n.get("to")) for n in query.get("normalized") or []}
    by_title = {str(page.get("title")): page for page in query.get("pages") or []}
    out: dict[str, dict] = {}
    for name in names:
        title = f"File:{name}"
        page = by_title.get(renamed.get(title, title)) or by_title.get(title.replace("_", " "))
        if page is not None:
            out[name] = page
    return out


def _search_pages(api: _Api, subject: str) -> list[dict]:
    data = api.get(_COMMONS_API, {
        "action": "query", "format": "json", "formatversion": "2",
        "generator": "search", "gsrsearch": f"{subject} filetype:bitmap",
        "gsrnamespace": "6", "gsrlimit": str(_SEARCH_LIMIT), **_IMAGE_INFO,
    }) or {}
    pages = list((data.get("query") or {}).get("pages") or [])
    return sorted(pages, key=lambda page: int(page.get("index") or 0))


def _subject_words(subject: str) -> set[str]:
    """The words a file name must carry to show the subject ('AI' of 'Liquid AI' included)."""
    return {w.casefold() for w in re.findall(r"[^\W\d_]{2,}", subject)}


def _names_subject(name: str, subject: str) -> bool:
    """True when a file name carries every word of the subject."""
    have = {w.casefold() for w in re.findall(r"[^\W\d_]+", name)}
    return _subject_words(subject) <= have


def _category_names_subject(category: str, subject: str) -> bool:
    """True when a category names the subject as one phrase.

    'Returned and Services League of Australia' holds both words of
    'Services Australia' and is about something else.
    """
    phrase = " ".join(_fold(subject).split())
    text = " ".join(_fold(category.replace("_", " ")).split())
    return bool(phrase) and re.search(rf"(?<![^\W_]){re.escape(phrase)}(?![^\W_])", text) is not None


def _searchable(subject: str, placed: bool) -> bool:
    """Whether a Commons keyword search can find this subject rather than its namesakes.

    Checked live: 'Mistral' found a warship and Mercury craters, 'GPT' a map
    of countries banning ChatGPT and 'MiMo' a street sign. A one-word subject
    is only searched when Wikidata placed it as a person, body or place.
    """
    return placed or len(_subject_words(subject)) >= 2


def _candidate(
    page: Optional[dict],
    subject: str,
    role: str,
    shows: str = "",
    position: int = 0,
    about: str = "",
    *,
    allow_share_alike: Optional[bool] = None,
) -> Optional[dict]:
    """One Commons file as a cover candidate, or None when it must not be offered."""
    if not isinstance(page, Mapping) or page.get("missing") or page.get("invalid"):
        return None
    info = (page.get("imageinfo") or [None])[0]
    if not isinstance(info, Mapping):
        return None
    title = str(page.get("title") or "")
    name = title.split(":", 1)[-1].replace("_", " ")
    mimes = _SEARCH_MIMES if role == "search" else _MIMES
    if str(info.get("mime") or "").lower() not in mimes:
        return None
    width, height = int(info.get("width") or 0), int(info.get("height") or 0)
    if not media_tools.image_fits_cover(width, height):
        return None
    meta = info.get("extmetadata") or {}
    licence = _plain(_meta(meta, "LicenseShortName"))
    categories = " | ".join(
        [str(c.get("title") or "") for c in page.get("categories") or []]
        + [_meta(meta, "Categories"), licence]
    )
    if _AI_CATEGORY_RE.search(categories) or media_tools._AI_ART_NAME_RE.search(name):
        return None
    if _NOT_A_PHOTO_RE.search(name):
        return None
    # A keyword search also matches descriptions: "Mistral Small" found a
    # flower show and "MiMo" a Bangkok junction. Its file name or its own
    # categories must name the subject.
    if role == "search" and not (
        _names_subject(name, subject)
        or any(_category_names_subject(category, subject) for category in categories.split("|"))
    ):
        return None
    if _meta(meta, "NonFree").strip().lower() in ("true", "1", "yes"):
        return None
    licence_rank = _licence_rank(licence, allow_share_alike)
    if licence_rank is None:
        return None
    credit = _credit(_meta(meta, "Artist"), licence)
    if not credit:
        return None
    url = str(info.get("thumburl") or info.get("url") or "")
    if not url:
        return None
    # The thumbnail API reports 1920 px even for a smaller original it serves
    # unscaled; report the size of what the URL actually returns.
    thumb_w = int(info.get("thumbwidth") or 0)
    if info.get("thumburl") and 0 < thumb_w < width:
        served = (thumb_w, int(info.get("thumbheight") or 0))
    else:
        served = (width, height)
    page_url = f"https://commons.wikimedia.org/wiki/{quote(title.replace(' ', '_'))}"
    # A leader's photo names the organisation too, so the judge knows why
    # Lei Jun is on a Xiaomi cover.
    who = f"{shows} ({subject})" if role == "leader" and shows and shows != subject else subject
    reason = {
        "subject": f"Wikidata photo of {subject}: {name} ({licence})",
        "leader": f"Wikidata photo of {shows or subject}, a leader or founder of {subject}: {name} ({licence})",
        "search": f"Wikimedia Commons search result for {subject}: {name} ({licence})",
    }[role]
    return {
        "url": url,
        "origin": "wikimedia",
        "score": _ROLE_SCORE[role] - 2 * licence_rank,
        "reason": reason,
        "context_url": str(info.get("descriptionurl") or page_url),
        "credit": credit,
        "licence": licence,
        "subject": who,
        # 'Xiaomi: Chinese electronics company', so the judge can tell the
        # company from a namesake.
        "about": about or who,
        "role": role,
        "width": served[0],
        "height": served[1],
        # A CEO before a chair or founder: each leader is a different person,
        # not a better or worse copy of the same picture. Search results keep
        # the search's own relevance order, never a licence order (a CC0
        # electrical panel once ranked first).
        "_sort": (
            (_ROLE_ORDER[role], int(page.get("index") or 0), 0, 0) if role == "search"
            else (_ROLE_ORDER[role], position, licence_rank, -min(width, height))
        ),
    }


def _clean_subjects(subjects: Any, limit: int = _MAX_SUBJECTS) -> list[str]:
    if isinstance(subjects, str):
        subjects = [subjects]
    out: list[str] = []
    for subject in subjects or []:
        text = " ".join(str(subject or "").split())[:120]
        if text and text.casefold() not in {s.casefold() for s in out}:
            out.append(text)
    return out[:max(limit, 0)]


def _lookup(
    api: _Api, subjects: list[str], context: frozenset[str], report: dict,
) -> list[tuple[int, dict]]:
    with ThreadPoolExecutor(max_workers=_WORKERS) as pool:
        per_subject = list(pool.map(
            lambda item: _wanted_files(api, item[0], item[1], context), enumerate(subjects),
        ))
        wanted = [entry for entries, _placed in per_subject for entry in entries]
        # One leader is one person: Lei Jun is Xiaomi's CEO, chair and founder,
        # and a second subject's item may name him again.
        seen_people: set[str] = set()
        unique = []
        for entry in wanted:
            person = entry[6]
            if person and person in seen_people:
                continue
            seen_people.add(person)
            unique.append(entry)
        pages = _commons_pages(api, [entry[2] for entry in unique])
        found: list[tuple[int, dict]] = []
        for index, role, name, who, position, about, _person in unique:
            candidate = _checked(pages.get(name), subjects[index], role, report, who, position, about)
            if candidate is not None:
                found.append((index, candidate))
        missing = [
            i for i, (subject, (_files, placed)) in enumerate(zip(subjects, per_subject))
            if not any(j == i for j, _c in found) and _searchable(subject, placed)
        ]
        searches = list(pool.map(lambda i: _search_pages(api, subjects[i]), missing))
    for index, pages_found in zip(missing, searches):
        kept = [
            c for c in (_checked(page, subjects[index], "search", report) for page in pages_found) if c
        ]
        found += [(index, candidate) for candidate in kept[:_SEARCH_KEEP]]
    return found


def _checked(
    page: Optional[dict], subject: str, role: str, report: dict, *args: Any,
) -> Optional[dict]:
    """:func:`_candidate`, counting files left out only for a share-alike licence."""
    candidate = _candidate(page, subject, role, *args)
    if (
        candidate is None
        and not _ALLOW_SHARE_ALIKE
        and _candidate(page, subject, role, *args, allow_share_alike=True) is not None
    ):
        report["share_alike_skipped"] = int(report.get("share_alike_skipped") or 0) + 1
    return candidate


def _in_turns(found: list[tuple[int, dict]], limit: int) -> list[dict]:
    """Every subject's best photos in turns, curated ones before any search hit.

    At most :data:`_PER_SUBJECT` per subject: in subject order the first
    subject's weak files filled every slot.
    """
    found = sorted(found, key=lambda item: (item[0], *item[1]["_sort"]))
    out: list[dict] = []
    taken: Counter[int] = Counter()
    urls: set[str] = set()
    for searched in (False, True):
        pools: dict[int, list[dict]] = {}
        for index, candidate in found:
            if (candidate["role"] == "search") is searched:
                pools.setdefault(index, []).append(candidate)
        while any(pools.values()):
            for index in sorted(pools):
                queue = pools[index]
                while queue:
                    candidate = queue.pop(0)
                    if candidate["url"] in urls or taken[index] >= _PER_SUBJECT:
                        continue
                    urls.add(candidate["url"])
                    taken[index] += 1
                    out.append(candidate)
                    break
                if taken[index] >= _PER_SUBJECT:
                    queue.clear()
    for candidate in out:
        candidate.pop("_sort", None)
    return out[:limit]


def reference_candidates(
    subjects: list[str],
    *,
    limit: int = 6,
    budget_s: float = 40.0,
    session: Any = None,
    context: str = "",
    report: Optional[dict] = None,
) -> list[dict]:
    """Free-licensed Commons photos of the story's subjects, best first.

    For each subject (at most four, in the order given): its Wikidata image
    (P18), the image of up to two of its leaders (CEO, chair, founder) and,
    when neither gives a usable file, a Commons search for the subject (for
    a one-word subject only when Wikidata placed it as a person, body or
    place; see :func:`_searchable`). Only an item whose label or alias is
    the subject is used, and among namesakes the one described in the
    story's words (``context``).

    Args:
        subjects: People, organisations, products or places, most important
            first (see :func:`story_subjects`).
        limit: Most candidates returned.
        budget_s: Wall-clock budget for all requests together.
        session: A ``requests.Session``-like object (tests pass a fake).
        context: The story's own text, to pick the right namesake.
        report: When given, ``share_alike_skipped`` counts the photos left
            out only because share-alike licences are off.

    Returns:
        ``image_candidates``-style dicts: url (the API's thumbnail URL,
        verbatim), origin 'wikimedia', score, reason, context_url (the file's
        Commons page), credit ('<Artist> / Wikimedia Commons, <licence>',
        plus "(cropped, text added)" for an attribution licence), licence,
        subject, about ('<label>: <Wikidata description>'), role ('subject' |
        'leader' | 'search'), width and height. The subjects take turns, at
        most two photos each, Wikidata photos before any search result;
        within a subject by role, licence (public domain, then attribution,
        then share-alike) and the larger short side, and search results in
        the search's own order. Never raises: a failed or timed-out request
        skips its step, and anything unexpected returns [].
    """
    report = report if report is not None else {}
    try:
        names = _clean_subjects(subjects)
        if not names or limit <= 0:
            return []
        own = session is None
        http = requests.Session() if own else session
        try:
            found = _lookup(_Api(http, budget_s), names, frozenset(_context_words(context)), report)
        finally:
            if own:
                http.close()
        return _in_turns(found, limit)
    except Exception:  # noqa: BLE001 - a free extra rung; never lose the cover over it
        logger.warning("Reference photo lookup failed for %s", subjects, exc_info=True)
        return []


def official_sites(
    subjects: list[str],
    *,
    budget_s: float = 8.0,
    session: Any = None,
    context: str = "",
    limit: int = _MAX_SUBJECTS,
) -> list[str]:
    """The official websites (Wikidata P856) of the story's subjects.

    mi.com for Xiaomi: its MiMo pages match no subject name, so without this
    the cover judge could not tell Xiaomi's own artwork from a fan site's.
    Same item rules as :func:`reference_candidates`, for up to ``limit``
    subjects (the cover's official check reads more names than the photo
    lookup). Never raises.
    """
    try:
        names = _clean_subjects(subjects, limit)
        if not names:
            return []
        own = session is None
        http = requests.Session() if own else session
        try:
            api = _Api(http, budget_s)
            words = frozenset(_context_words(context))
            with ThreadPoolExecutor(max_workers=_WORKERS) as pool:
                ids = [found[0] for found in pool.map(lambda s: _entity(api, s, words), names) if found[0]]
            entities = _entities(api, ids, "claims") if ids else {}
        finally:
            if own:
                http.close()
        sites: list[str] = []
        for entity in entities.values():
            for site in _statements((entity or {}).get("claims") or {}, "P856"):
                if isinstance(site, str) and site.startswith(("http://", "https://")) and site not in sites:
                    sites.append(site)
        return sites
    except Exception:  # noqa: BLE001 - a free helper; never lose the cover over it
        logger.warning("Official website lookup failed for %s", subjects, exc_info=True)
        return []


# upload.wikimedia.org/wikipedia/<project>/[thumb/]a/ab/<File>[/<N>px-<File>]
_UPLOAD_PATH_RE = re.compile(r"^/wikipedia/([a-z-]+)/(?:thumb/)?[0-9a-f]/[0-9a-f]{2}/([^/]+)")


def wikimedia_file(url: str) -> Optional[tuple[str, str]]:
    """(project, file name) of a Wikimedia upload URL ('commons', 'Name.jpg'), else None."""
    parsed = urlparse(str(url or ""))
    host = (parsed.hostname or "").lower()
    if not (host == "wikimedia.org" or host.endswith(".wikimedia.org")):
        return None
    match = _UPLOAD_PATH_RE.match(parsed.path)
    return (match[1], unquote(match[2])) if match else None


def file_credit(url: str, *, budget_s: float = 10.0, session: Any = None) -> Optional[dict]:
    """The credit and licence of a Wikimedia file the cover found elsewhere.

    A research page can link an upload.wikimedia.org picture directly; it
    then reached the cover with no credit at all, and a Wikipedia page's
    local files are often non-free (logos, posters).

    Returns:
        None when ``url`` is not a Wikimedia upload or the lookup failed;
        otherwise ``{reusable, credit, licence, context_url, title}``, with
        ``reusable`` false when the licence is not on the allowlist.
    """
    found = wikimedia_file(url)
    if found is None:
        return None
    project, name = found
    api_url = _COMMONS_API if project == "commons" else f"https://{project}.wikipedia.org/w/api.php"
    try:
        own = session is None
        http = requests.Session() if own else session
        try:
            data = _Api(http, budget_s).get(api_url, {
                "action": "query", "format": "json", "formatversion": "2",
                "titles": f"File:{name}", **_IMAGE_INFO,
            }) or {}
        finally:
            if own:
                http.close()
        pages = (data.get("query") or {}).get("pages") or []
        page = pages[0] if pages and isinstance(pages[0], Mapping) else {}
        info = (page.get("imageinfo") or [None])[0]
        if not isinstance(info, Mapping):
            return None
        meta = info.get("extmetadata") or {}
        licence = _plain(_meta(meta, "LicenseShortName"))
        nonfree = _meta(meta, "NonFree").strip().lower() in ("true", "1", "yes")
        credit = _credit(_meta(meta, "Artist"), licence)
        reusable = not nonfree and _licence_rank(licence) is not None and bool(credit)
        title = str(page.get("title") or f"File:{name}")
        site = "commons.wikimedia.org" if project == "commons" else f"{project}.wikipedia.org"
        page_url = f"https://{site}/wiki/{quote(title.replace(' ', '_'))}"
        return {
            "reusable": reusable,
            "credit": credit if reusable else "",
            "licence": licence,
            "context_url": str(info.get("descriptionurl") or page_url),
            "title": title,
        }
    except Exception:  # noqa: BLE001 - a free helper; never lose the cover over it
        logger.warning("Wikimedia credit lookup failed for %s", url, exc_info=True)
        return None


# ---------------------------------------------------------------------------
# story_subjects
# ---------------------------------------------------------------------------


def _is_name_word(word: str) -> bool:
    """Capitalised, CamelCase (OpenAI, iPhone) or an acronym, with 3 or more letters."""
    return (
        sum(ch.isalpha() for ch in word) >= 3
        and any(ch.isupper() for ch in word)
        and word.casefold() not in _STOPWORDS
    )


def _shouted(words: list[str]) -> set[int]:
    """Positions of words in an all-caps stretch ('AI MODELS RACE ON SPEED'): headline shouting, not acronyms."""
    caps = [bool(re.fullmatch(r"[A-Z][A-Z0-9]+", _POSSESSIVE_RE.sub("", w))) for w in words]
    out: set[int] = set()
    start = 0
    for index in range(len(words) + 1):
        if index < len(words) and caps[index]:
            continue
        if index - start >= _SHOUTED_RUN:
            out.update(range(start, index))
        start = index + 1
    return out


def _names_in(text: str, *, join: bool = True) -> list[str]:
    """Runs of name words in one piece of text: 'Prime Minister Anthony Albanese' -> 'Anthony Albanese'."""
    names: list[str] = []
    text = straight_quotes(str(text or "").translate(_DASHES))
    for chunk in _NAME_BREAK_RE.split(text):
        words = chunk.split()
        shouted = _shouted(words)
        run: list[str] = []
        for position, raw in enumerate(words):
            word_match = _WORD_RE.match(raw)
            word = word_match.group(0) if word_match and position not in shouted else ""
            possessive = bool(_POSSESSIVE_RE.search(raw))
            # A word glued to something else (GPT-5.4, DeepSeek-V3.2) ends the name.
            ends = not join or possessive or word != raw
            if run and join and word.isupper() and len(word) == 2:
                ends = True  # 'Mistral AI', 'Liquid AI': a short acronym only ends a name
            elif word and _is_name_word(word):
                if run and word.casefold() in _DEMONYMS:
                    names.append(" ".join(run))  # 'an OpenAI Australian government hack'
                    run = []
            else:
                if run:
                    names.append(" ".join(run))
                run = []
                continue
            run.append(word)
            if ends or len(run) >= _MAX_NAME_WORDS:
                names.append(" ".join(run))
                run = []
        if run:
            names.append(" ".join(run))
    return names


def _has_case_signal(text: str) -> bool:
    """False for an all-lowercase or shouting title: its capitals name nothing."""
    words = [w for w in re.findall(r"[A-Za-z]{2,}", text)]
    if not words or not any(ch.isupper() for ch in text):
        return False
    return sum(w.isupper() for w in words) * 2 <= len(words)


def _is_title_case(text: str) -> bool:
    words = [w for w in _WORD_RE.findall(text) if len(w) >= 4]
    return len(words) >= 3 and sum(w[0].isupper() for w in words) >= 0.7 * len(words)


def _prose(text: str) -> str:
    """Only the sentences of a text; a scraped page's menus and bylines are dropped."""
    lines = str(text or "").splitlines()
    return "\n".join(line for line in lines if len(line.split()) >= _MIN_PROSE_WORDS)


def story_subjects(
    news: Optional[dict],
    research: Optional[dict] = None,
    plan: Optional[dict] = None,
    *,
    limit: int = 4,
) -> list[str]:
    """The people, organisations, products and places the story names most.

    Read from the news title (unless it carries no capitals to go by), the
    news summary, the research summary and its first key facts, and the
    plan's hook and slide points; a name the hook repeats goes first, even
    when the hook is in capitals. Consecutive capitalised, CamelCase or
    acronym words form one name; months, weekdays, sentence starters and
    job titles are left out. A surname used alone ('Albanese said') counts
    toward the full name it shortens ('Anthony Albanese'). Ranked by how often
    each name appears; on a tie a person (a full name also used by its
    surname) comes first, then a multi-word name.
    """
    texts: list[tuple[str, bool]] = []  # (text, join words into names)
    news = news if isinstance(news, Mapping) else {}
    research = research if isinstance(research, Mapping) else {}
    plan = plan if isinstance(plan, Mapping) else {}
    title = str(news.get("title") or "")
    if _has_case_signal(title):
        texts.append((title, not _is_title_case(title)))
    texts.append((_prose(news.get("summary")), True))
    texts.append((str(research.get("summary") or ""), True))
    for fact in list(research.get("key_facts") or [])[:_FACTS_READ]:
        text = fact.get("fact") if isinstance(fact, Mapping) else fact
        texts.append((str(text or ""), True))
    hook = str(plan.get("hook_title") or "")
    if _has_case_signal(hook):
        texts.append((hook, not _is_title_case(hook)))
    for slide in list(plan.get("slides") or []):
        if isinstance(slide, Mapping):
            texts += [(str(point or ""), True) for point in slide.get("key_points") or []]

    counts: Counter[str] = Counter()
    first_seen: dict[str, int] = {}
    spelling: dict[str, str] = {}
    for text, join in texts:
        for name in _names_in(text, join=join):
            key = name.casefold()
            counts[key] += 1
            first_seen.setdefault(key, len(first_seen))
            spelling.setdefault(key, name)
    # 'Albanese' alone is the surname of 'Anthony Albanese': a Wikidata search
    # for the surname finds the family name, not the prime minister. Only a
    # full name written before the short one counts, the way news copy names
    # people: 'Australia' in the headline is not short for 'Services Australia'.
    people: set[str] = set()
    for key in [k for k in counts if " " not in k]:
        longer = [k for k in counts if k.endswith(f" {key}") and first_seen[k] < first_seen[key]]
        if longer:
            best = max(longer, key=lambda k: (counts[k], -first_seen[k]))
            counts[best] += counts.pop(key)
            people.add(best)
    # A nationality alone ('Australian') names no one to photograph.
    for key in [k for k in counts if k in _DEMONYMS]:
        counts.pop(key)
    # The cover's own hook says what the cover is about, even when it is
    # shouted ('XIAOMI CHARGES 10X MORE FOR FASTER AI' gives no names of its
    # own): a name found elsewhere whose words it repeats goes first.
    hook_words = {
        _POSSESSIVE_RE.sub("", _fold(word).strip(".,;:!?\"()"))
        for word in straight_quotes(hook).translate(_DASHES).replace("-", " ").split()
    }
    in_hook = {key for key in counts if all(_fold(word) in hook_words for word in key.split())}
    # On a tie a person goes first (a face makes the strongest cover), then
    # any multi-word name, then the name the story used first.
    ranked = sorted(
        counts,
        key=lambda k: (k not in in_hook, -counts[k], k not in people, " " not in k, first_seen[k]),
    )
    return [spelling[key] for key in ranked[: max(limit, 0)]]


__all__ = [
    "file_credit", "official_sites", "reference_candidates", "story_subjects", "wikimedia_file",
]
