"""Build fixed RPC SQL and the matching typed client catalog from app queries.

Development/migration utility only: --dsn-env names an existing local env key
for schema inspection. No SQL text from HTTP callers is ever executed.
"""
import argparse
import ast
import asyncio
import importlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
import asyncpg
from dotenv import dotenv_values
from app.services.supabase_db import normalize_sql, operation_id

MODULES = ['app.services.db','app.services.memory_service','web_api.routes_runs',
           'app.review.verdict','app.runs.recovery']


def queries():
    result = {}
    for name in MODULES:
        module = importlib.import_module(name)
        tree = ast.parse(Path(module.__file__).read_text(encoding='utf-8-sig'))
        for node in ast.walk(tree):
            if not isinstance(node,ast.Call) or not isinstance(node.func,ast.Attribute): continue
            if node.func.attr not in ('fetch','fetchrow','fetchval','execute','executemany') or not node.args: continue
            try:
                sql = eval(compile(ast.Expression(node.args[0]),'<query>','eval'),vars(module))
            except Exception as exc:
                raise RuntimeError(f'Non-static SQL in {name}:{node.lineno}; use a fixed query') from exc
            if not isinstance(sql,str) or not re.match(r'\s*(SELECT|INSERT|UPDATE|DELETE|WITH)\b',sql,re.I):
                raise RuntimeError(f'Unexpected SQL in {name}:{node.lineno}')
            result[normalize_sql(sql)] = f'{name}:{node.lineno}'
    return result


async def build(dsn_env):
    dsn = dotenv_values(ROOT/'.env').get(dsn_env)
    if not dsn: raise RuntimeError('Schema inspection needs the named local connection setting')
    conn = await asyncpg.connect(dsn.replace('+asyncpg','',1),statement_cache_size=0)
    transaction = conn.transaction()
    await transaction.start()
    await conn.execute('ALTER TABLE public.runs ADD COLUMN IF NOT EXISTS title_locked boolean NOT NULL DEFAULT false')
    catalog = {}
    ddl = ['-- Generated by scripts/build_db_rpc.py; fixed SQL only.\nBEGIN;\n'
           'ALTER TABLE public.runs ADD COLUMN IF NOT EXISTS title_locked boolean NOT NULL DEFAULT false;\n'
           'CREATE SCHEMA IF NOT EXISTS carousel_internal;\n'
           'REVOKE ALL ON SCHEMA carousel_internal FROM PUBLIC, anon, authenticated;']
    dispatch = []
    try:
        for sql,source in sorted(queries().items()):
            try:
                prepared = await conn.prepare(sql)
            except Exception as exc:
                raise RuntimeError(f'Cannot prepare {source}: {type(exc).__name__}') from exc
            types = [p.name for p in prepared.get_parameters()]
            columns = [{'name':p.name,'type':p.type.name} for p in prepared.get_attributes()]
            identifier = operation_id(sql)
            command = re.match(r'\w+',sql)[0].upper()
            catalog[identifier] = {'sql':sql,'parameters':types,'columns':columns,'command':command,'source':source}
            def argument(match):
                i = int(match[1])-1
                typ = types[i]
                if typ in ('json','jsonb'): return f'(params->{i})::{typ}'
                if typ.startswith('_') or typ.endswith('[]'):
                    base=typ[1:] if typ.startswith('_') else typ[:-2]
                    return f'(CASE WHEN params->{i}=\'null\'::jsonb THEN NULL ELSE ARRAY(SELECT jsonb_array_elements_text(params->{i}))::{base}[] END)'
                return f'(params->>{i})::{typ}'
            bound = re.sub(r'\$(\d+)\b',argument,sql)
            check = f"IF jsonb_typeof(params) IS DISTINCT FROM 'array' OR jsonb_array_length(params)<>{len(types)} THEN RAISE EXCEPTION 'Invalid RPC arguments'; END IF;"
            if columns:
                # A data-modifying CTE preserves RETURNING and atomicity.
                body = f'WITH result AS ({bound}) SELECT jsonb_build_object(\'rows\',COALESCE(jsonb_agg(to_jsonb(result)),\'[]\'::jsonb),\'count\',count(*)) INTO output FROM result;'
            else:
                body = bound + "; GET DIAGNOSTICS affected = ROW_COUNT; output := jsonb_build_object('rows','[]'::jsonb,'count',affected);"
            ddl.append(f'''-- {source}
CREATE OR REPLACE FUNCTION carousel_internal.{identifier}(params jsonb) RETURNS jsonb
LANGUAGE plpgsql SET search_path=pg_catalog,public AS $rpc$
DECLARE output jsonb; affected bigint;
BEGIN {check} {body} RETURN output; END $rpc$;
REVOKE ALL ON FUNCTION carousel_internal.{identifier}(jsonb) FROM PUBLIC,anon,authenticated;
''')
            dispatch.append(f"WHEN '{identifier}' THEN RETURN carousel_internal.{identifier}(params);")
        ddl.append('''CREATE OR REPLACE FUNCTION public.carousel_query(operation text, params jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $rpc$
BEGIN CASE operation
'''+ '\n'.join(dispatch)+'''
ELSE RAISE EXCEPTION 'Unknown database operation'; END CASE; END $rpc$;
REVOKE ALL ON FUNCTION public.carousel_query(text,jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.carousel_query(text,jsonb) TO service_role;
CREATE OR REPLACE FUNCTION public.carousel_query_batch(operation text, batches jsonb) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $rpc$
DECLARE args jsonb;
BEGIN
 IF jsonb_typeof(batches) IS DISTINCT FROM 'array' THEN RAISE EXCEPTION 'Invalid batches'; END IF;
 FOR args IN SELECT value FROM jsonb_array_elements(batches) LOOP
  PERFORM public.carousel_query(operation,args);
 END LOOP;
END $rpc$;
REVOKE ALL ON FUNCTION public.carousel_query_batch(text,jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.carousel_query_batch(text,jsonb) TO service_role;
NOTIFY pgrst,'reload schema';
COMMIT;
''')
        (ROOT/'app/services/db_operations.json').write_text(json.dumps(catalog,indent=2)+'\n')
        (ROOT/'db/migrations/010_https_query_operations.sql').write_text('\n'.join(ddl))
        print('Built',len(catalog),'fixed query operations.')
    finally:
        await transaction.rollback()
        await conn.close()


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--dsn-env',default='MIGRATION_DATABASE_URL')
    asyncio.run(build(parser.parse_args().dsn_env))
